### ISSUE TITLE
Microsoft Solitaire Collection has been updated

### ISSUE THREAD

**Issue by mchung94** [mchung94/solitaire-player#1]
There's a new update to Microsoft Solitaire Collection, where the graphics, position of cards in the window, and the Undo Board / OK buttons have changed.  So the program won't be able to detect the cards and play the game properly.

I'll be working on an update to keep the program working, but I won't be able to properly support 200% and 250% windows display scaling anymore, only 100%.

**Comment by 0xDECEA5ED** [comment]
This seems to have happened again sometime between the latest release and today. The Undo Board button has changed, and the application cannot play the game properly.

**Comment by mchung94** [comment]
Thanks for letting me know! I've just released a new version to fix this problem, version 2.4.2: https://github.com/mchung94/solitaire-player/releases/tag/v2.4.2

Please let me know if the new version is not working for you.
