### ISSUE TITLE
Can't detect Pyramid Solitaire

### ISSUE THREAD

**Issue by AndnixSH** [mchung94/solitaire-player#19]
It seems it does not detect Pyramid Solitaire even though i'm playing it
TriPeaks working fine and I have changed system language to english (US)

```
Starting a Pyramid Solitaire Board Challenge...
System Report:
    Window Size (after adjustment) = 1440x900
    Expected Window Size = 1440x900
    DPI = 96
    Expected DPI = 96
    Scaling Factor = 100.0%
    Primary Screen Size (Adjusted for Scaling Factor) = 1920x1080
    Expected Primary Screen Size = 1920x1080
If the scaling factor isn't 100% or the values don't match the expected,
then this program may not work properly.
Can't detect if we're playing a game of Pyramid Solitaire.
```

**Comment by cou94114** [comment]
I think this may be related to the latest update from Microsoft. 

Microsoft Solitaire Collection version 4.11.12030.0

**Comment by mchung94** [comment]
Thanks for pointing out the problem! I created a new release that should make Pyramid Solitaire work again at https://github.com/mchung94/solitaire-player/releases/tag/v2.6.4

**Comment by AndnixSH** [comment]
It works with the new version now

Btw, can you add an option to specify a number how many times to run like `solitaire-player.bat Pyramid Board 2` ? can be useful for Star Club
