### ISSUE TITLE
Have to open the windows 10 cmd to access the code

### ISSUE THREAD

**Issue by Mstumr** [mchung94/solitaire-player#28]

**Comment by Mstumr** [comment]
Clicking the .bat file makes the cmd show up and then disappear, I have to access it through the window cmd to make it work.

**Comment by mchung94** [comment]
Thanks for opening the issue! I'll look into this, it was originally designed to work from the Windows command line app so you can tell it what options you want, but I'll try to think of how I can make it work by just clicking on the .bat file.
