### ISSUE TITLE
Critical error, the code no longer work after java update, or may be its just a little bug (I think so)

### ISSUE THREAD

**Issue by Mstumr** [mchung94/solitaire-player#30]
![Screenshot 2022-10-07 231829](https://user-images.githubusercontent.com/104849582/194600898-a4870a49-12dd-4fb2-8cd7-f3e0f4718298.png)

**Comment by mchung94** [comment]
Hi,
This looks like you're running Java 8 instead of Java 11.
One thing to try is run "java -version" on the command line and see if it says 8 or 11.

If you're running Java 8 for another program maybe it's not a good idea to switch to 11 just to run this program though.

**Comment by Mstumr** [comment]
Can you explain more about Java 11 and installing it? Is it a runtime environment or a development kit? I searched for Java 11 RE but there was no result. I had tried installing jDK 11 and furthermore, but nothing worked. Many people advised me to install later versions of Java to make my programs run better. (Ye I don't know much about Java because it is not my forte).

**Comment by mchung94** [comment]
I made a short youtube video on the steps I took: https://youtu.be/X8KebEPLLeY

Basically I go to https://adoptium.net and then download the Java 11 JDK for Windows (Architecture x64, Package Type JDK, Version 11) and download the MSI file (not the ZIP file)
Then I double click the msi file and it'll install Java 11.

You can check it in the command prompt by running "java --version" and it should print out:
openjdk 11.0.16.1 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)

**Comment by Mstumr** [comment]
Thanks for your dedication! Everything is working fine. I think many people will need this. I think I will be looking forward to Java 19.
