### ISSUE TITLE
The mouse cursor points at a wrong section to click "undo all"

### ISSUE THREAD

**Issue by 20LeeBrian1** [mchung94/solitaire-player#5]
Hello,

I really enjoy your program so far! I had a slight concern (especially the TriPeaks) about your program: the mouse cursor points in the wrong part after i click ok after scanning. It is supposed to click "undo all," but it went to the wrong way and produced erroneous solutions even though there is a solution. While this is corrected manually, it is pretty annoying. Thank you!

**Comment by mchung94** [comment]
Hi,

Thanks for letting me know! I just made a new release (version 2.4.2) to fix this problem: https://github.com/mchung94/solitaire-player/releases/tag/v2.4.2

Please let me know if it's still causing a problem.
