### ISSUE TITLE
Incorrect score calculation for TriPeaks games

### ISSUE THREAD

**Issue by 0xDECEA5ED** [mchung94/solitaire-player#6]
Score is  overestimated for TriPeaks games and in TriPeaks tests.

Score method in solvers/tripeaks/ScoreChallengeSolver.java should be calculated as `total += 100 + streak * 200;` instead of `total += 300 + streak * 200;`
MAX_POSSIBLE_SCORE should be 84900.

Tests will need to be updated to ensure correct functionality.
See my fork for my fixes.

**Comment by mchung94** [comment]
Thanks for catching the problem and also for the fixes in your fork!
